### ISSUE TITLE
Add a link to the default Eclipse Kuksa website

### ISSUE THREAD

**Issue by phkrief** [eclipse/kuksa.website#2]
A link is missing to reach the default website provided by the Eclipse forge: 
https://projects.eclipse.org/projects/iot.kuksa

**Comment by rohoet** [comment]
We could replace _forum_ by _community_ and have drop-down entries such as _forum, who's involved, contribute, issues_, ... WDYT?

**Comment by rohoet** [comment]
Ok, I added the PMI community tab, linking to the default eclipse kuksa website, i.e., Eclipse PMI community.
We can figure out how to use a submenu later on.
