### ISSUE TITLE
New documentation requires major revision

### ISSUE THREAD

**Issue by rohoet** [eclipse/kuksa.website#21]
Currently located in staging branch.

Check / Update

- [x] Links
- [x] Duplicate text from readme files
- [x] Deprecated content (remove)
- [x] Images

**Comment by eriksven** [comment]
I noticed that major parts in the documentation document on the staging branch have been uncommented. For me it is fine to leave them out. When do we want to remove them?

**Comment by eriksven** [comment]
Finished the revision of the cloud section in #22

**Comment by rohoet** [comment]
Thanks for the cloud section update!
Regarding the commented-out cloud documentation: Do you know where that comes from?

The structure is odd / not in line with the rest of the documentation and content-wise, it seems quite generic, is partially not representing the current state but rather ideas / outlooks, and sometimes lacks in information / explanation / examples.

I do not feel comfortable with _aligning_ this part and hence commented it in c864cb8.

**Comment by eriksven** [comment]
I agree, that it will be hard to align the commented sections for the reasons @rohoet outlined. That  is why I would fully remove them. My comment above was more directed to all commented sections. For the cloud section I will go ahead and remove it.

**Comment by rohoet** [comment]
For me, commenting was just the **quickest** way to form an initial _reasonable_ documentation. I agree to remove those part for process of merging staging into master.
I guess, tracking the progress here should be enough to recall what happened.

**Comment by rohoet** [comment]
Closed via d22359e7
