### ISSUE TITLE
Add a page embedding the Wiki provides by Eclipse

### ISSUE THREAD

**Issue by phkrief** [eclipse/kuksa.website#3]

**Comment by eriksven** [comment]
My proposal is to consolidate the documentation in the Kuksa website (currently prepared in staging branch) and thus to only link to that documentation from the Eclipse Wiki. As a consequence, we would not embed the wiki into the website and would close this issue. What do the other think?

**Comment by rohoet** [comment]
Sounds good! Let's include the link in the wiki as soon as staging is merged.

**Comment by SebastianSchildt** [comment]
Obsolete
