### ISSUE TITLE
Add Incubation Egg to Website

### ISSUE THREAD

**Issue by rohoet** [eclipse/kuksa.website#6]
[Incubation Egg](https://wiki.eclipse.org/images/d/d4/Egg-incubation.png)

**Comment by phkrief** [comment]
Hi Robert,
Where would you like to put it? 
For now, the only idea I have in mind is to put it next to the Kuksa logo.
Do you have a better idea ?
Thx

**Comment by phkrief** [comment]
Robert, I updated the staging. WDYT?
https://staging.eclipse.org/kuksa/

**Comment by rohoet** [comment]
Cheers Philippe! Looks fine, thanks.
